#ifndef OPDCODE_H
#define OPDCODE_H

// STOPS THE PROGRAM.
#define OP_HALT 0x00
// PUSHES A CONST ONTO THE STACK.
#define OP_CONST 0x01
// MATH INSTRUCTION.
#define OP_ADD 0x02
#define OP_SUB 0x03
#define OP_MUL 0x04
#define OP_DIV 0x05
// COMPARE INSTRUCTION.
#define OP_COMPARE 0x06

#endif