%lex

%%

\s+               /* Ignore whitespace */

\"[^\"]*\"         return 'STRING'

\d+               return 'NUMBER'

[\w\-+*=<>/]+     return 'SYMBOL'

/lex

%%

Exp
  : Atom
  | List
  ;

Atom
  : NUMBER { $$ = Number($1); }
  | STRING { $$ = $1.slice(1, -1); }  /* Remove quotes from STRING */
  | SYMBOL { $$ = $1; }
  ;

List
  : '(' ListEntries ')' { $$ = $2; }
  ;

ListEntries
  : ListEntries Exp { $1.push($2); $$ = $1; }
  | /* empty */ { $$ = []; }
  ;
